import { Avatar } from './lib/shooting/avatar';

export const AvatarsDemo = [
  {
    name: 'タローくん',
    imageUrl: '/k-taro.png',
    message: 'えぇ〜〜',
    favorite: 'Web',
    firstMet: new Date('2024-09-15'),
    level: 1,
    defeats: 25,
    numberOfFavorites: 36,
    height: 1,
    weight: 1,
  },
  {
    name: 'ひなりん',
    imageUrl: '/hinalin.png',
    message: 'Gradleよりも強敵だ！！',
    favorite: 'Kotlin',
    firstMet: new Date('2024-09-15'),
    level: 1,
    defeats: 25,
    numberOfFavorites: 36,
    height: 1,
    weight: 1,
  },
  {
    name: '浦くん',
    imageUrl: '/ura.png',
    message: 'ぎゃー',
    favorite: 'ハンバーグ',
    firstMet: new Date('2024-09-15'),
    level: 1,
    defeats: 25,
    numberOfFavorites: 36,
    height: 1,
    weight: 1,
  },
  {
    name: '大先生',
    imageUrl: '/yutotuy.png',
    message: 'ぎゃー',
    favorite: 'ハンバーグ',
    firstMet: new Date('2024-09-15'),
    level: 1,
    defeats: 25,
    numberOfFavorites: 36,
    height: 1,
    weight: 1,
  },
  {
    name: 'たまちゃ',
    imageUrl: '/tamacha.png',
    message: 'ぎゃー',
    favorite: 'ハンバーグ',
    firstMet: new Date('2024-09-15'),
    level: 1,
    defeats: 25,
    numberOfFavorites: 36,
    height: 1,
    weight: 1,
  },
] as const satisfies Avatar[];
